"""Default parameter dictionaries used by nodes and the YAML config."""

from __future__ import annotations

from typing import Any, Dict


PLANT_DEFAULTS: Dict[str, Any] = {
    "update_rate_hz": 500.0,
    "mujoco.xml_path": "",
    "mujoco.enable": True,
    "mujoco.launch_viewer": True,
    "motor.inertia_kg_m2": 0.00012,
    "motor.viscous_damping_nm_s_per_rad": 0.0002,
    "motor.coulomb_friction_nm": 0.0003,
    "motor.static_friction_nm": 0.0005,
    "motor.stiffness_nm_per_rad": 0.0,
    "motor.torque_constant_nm_per_a": 0.11,
    "finger.inertia_kg_m2": 0.00018,
    "finger.length_m": 0.09,
    "finger.mass_kg": 0.055,
    "finger.com_length_m": 0.045,
    "finger.viscous_damping_nm_s_per_rad": 0.0015,
    "finger.coulomb_friction_nm": 0.0008,
    "finger.static_friction_nm": 0.0012,
    "finger.joint_stiffness_nm_per_rad": 0.02,
    "finger.enable_gravity": True,
    "friction.stiction_velocity_rad_s": 0.025,
    "transmission.gear_ratio": 5.0,
    "transmission.spool_radius_m": 0.012,
    "transmission.spool_inertia_kg_m2": 0.00035,
    "transmission.spool_viscous_damping_nm_s_per_rad": 0.0002,
    "transmission.spool_coulomb_friction_nm": 0.0002,
    "transmission.tendon_moment_arm_m": 0.018,
    "tendon.stiffness_n_per_m": 850.0,
    "tendon.damping_n_s_per_m": 1.5,
    "tendon.slack_m": 0.001,
    "backlash.motor_deadband_rad": 0.025,
    "backlash.output_deadband_mm": 0.5,
    "sensors.encoder_counts_per_rev": 4096.0,
    "sensors.encoder_noise_std_rad": 0.0008,
    "sensors.encoder_velocity_noise_std_rad_s": 0.004,
    "sensors.output_sensor_enabled": True,
    "sensors.output_sensor_noise_std_rad": 0.0012,
    "sensors.output_sensor_velocity_noise_std_rad_s": 0.006,
    "sensors.random_seed": 7,
    "delay.command_delay_s": 0.005,
    "delay.measurement_delay_s": 0.004,
    "load.external_torque": 0.0,
    "actuator.torque_lag_time_constant_s": 0.008,
    "thermal.ambient_temperature_c": 25.0,
    "thermal.heating_coeff_c_per_a2_s": 0.09,
    "thermal.cooling_coeff_per_s": 0.025,
    "safety.max_position_rad": 1.35,
    "safety.min_position_rad": -0.05,
    "safety.min_motor_position_rad": 0.0,
    "safety.max_velocity_rad_s": 18.0,
    "safety.max_current_a": 2.5,
    "safety.min_torque_nm": 0.0,
    "safety.max_torque_nm": 0.35,
    "safety.max_temperature_c": 85.0,
}


CONTROLLER_DEFAULTS: Dict[str, Any] = {
    "update_rate_hz": 250.0,
    "feedback_source": "output_sensor",
    "target_position_rad": 0.0,
    "target_velocity_rad_s": 0.0,
    "position.kp": 4.0,
    "position.ki": 0.0,
    "position.kd": 0.0,
    "position.integral_limit": 1.0,
    "position.velocity_limit_rad_s": 1.5,
    "velocity.kp": 0.006,
    "velocity.ki": 0.0,
    "velocity.kd": 0.0,
    "velocity.integral_limit": 4.0,
    "velocity.minimum_torque_nm": 0.0,
    "velocity.torque_limit_nm": 0.275,
    "feedforward.velocity_gain_nm_per_rad_s": 0.0,
    "feedforward.acceleration_gain_nm_per_rad_s2": 0.0,
    "feedforward.gravity_compensation": True,
    "feedforward.joint_stiffness_compensation": True,
    "feedforward.friction_compensation": False,
    "model.finger_mass_kg": 0.055,
    "model.finger_com_length_m": 0.045,
    "model.finger_coulomb_friction_nm": 0.012,
    "model.finger_joint_stiffness_nm_per_rad": 0.02,
    "transmission.gear_ratio": 5.0,
    "transmission.spool_radius_m": 0.012,
    "transmission.tendon_moment_arm_m": 0.018,
    "motor.torque_constant_nm_per_a": 0.11,
    "safety.max_current_a": 2.5,
    "safety.max_torque_nm": 0.35,
}


LOGGER_DEFAULTS: Dict[str, Any] = {
    "output_directory": "data",
    "file_prefix": "testbench",
    "flush_every_n_rows": 25,
}


TEST_DEFAULTS: Dict[str, Any] = {
    "mode": "step",
    "auto_start": False,
    "output_directory": "data",
    "duration_s": 8.0,
    "start_delay_s": 1.0,
    "publish_rate_hz": 50.0,
    "step.target_rad": 0.75,
    "step.hold_s": 5.0,
    "backlash.amplitude_rad": 0.65,
    "backlash.cycles": 4.0,
    "backlash.period_s": 3.0,
    "friction.amplitude_rad": 0.9,
    "friction.period_s": 12.0,
    "sine.amplitude_rad": 0.45,
    "sine.bias_rad": 0.55,
    "sine.frequency_hz": 0.5,
    "chirp.amplitude_rad": 0.45,
    "chirp.bias_rad": 0.55,
    "chirp.start_frequency_hz": 0.1,
    "chirp.end_frequency_hz": 3.0,
    "load.target_rad": 0.8,
    "load.external_torque_nm": 0.08,
    "thermal.amplitude_rad": 0.55,
    "thermal.bias_rad": 0.55,
    "thermal.frequency_hz": 0.8,
    "transmission.gear_ratio": 5.0,
    "transmission.spool_radius_m": 0.012,
    "transmission.tendon_moment_arm_m": 0.018,
    "finger.length_m": 0.09,
}


CLI_DEFAULTS: Dict[str, Any] = {
    "transmission.gear_ratio": 5.0,
    "transmission.spool_radius_m": 0.012,
    "transmission.tendon_moment_arm_m": 0.018,
    "finger.length_m": 0.09,
}
